name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      # 1️⃣ Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # 3️⃣ Instalar dependencias compatibles
      - name: Install dependencies
        run: |
          npm install typescript@5.9.3 ts-node@latest jest ts-jest @types/jest --save-dev --legacy-peer-deps
          npm install
          npm install @playwright/test@1.57.0 playwright@1.57.0 --save-dev

      # 4️⃣ Levantar el mock server y esperar a que esté listo
      - name: Start mock server
        run: |
         node --loader ts-node/esm qa-agentic-framework-ts/mockServer.ts &
         echo $! > server.pi

      # 5️⃣ Levantar servidor estático para las pruebas E2E
      - name: Start HTML server
        run: |
          npx serve public --listen 3000 &
          echo $! > serve.pid
          sleep 3
         

      # 5️⃣ Ejecutar tests con Jest
      - name: Run tests
        run: npx jest --config jest.config.js tests/api.test.
        
      # 7️⃣ Ejecutar test específico de Playwright (E2E)
      - name: Run specific Playwright test
        run: npx playwright test tests/e2e.test.ts

      # 6️⃣ Terminar el servidor
      - name: Stop mock server
        if: always()
        run: |
          kill $(cat server.pid) || true
          kill $(cat serve.pid) || true